name: Push

on:
  push:
    branches:
      - main

jobs:
  flake-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix Flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Allow direnv
        run: nix develop .#default -c direnv allow .

      - name: Export direnv
        run: nix develop .#default -c direnv export gha >> "$GITHUB_ENV"

      - name: Build Docker stream script
        run: nix build .#dockerStream --out-link docker-image-stream

      - name: Load Docker image
        run: ./docker-image-stream | docker load

      - name: Authenticate to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Tag Docker image
        run: docker tag reloader:latest ghcr.io/${{ github.repository }}:${{ github.sha }} && docker tag reloader:latest ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }} && docker push ghcr.io/${{ github.repository }}:latest
