name: Push

on:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix Flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Allow direnv
        run: nix develop .#default -c direnv allow .

      - name: Export direnv
        run: nix develop .#default -c direnv export gha >> "$GITHUB_ENV"

      - name: Build Image
        run: nix build .#stream

      - name: Push Image
        run: ./result | gzip --fast | skopeo copy --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" docker-archive:/dev/stdin docker://ghcr.io/${{ github.repository }}:${{ github.sha }}
