name: Push

on:
  push:
    branches:
      - main

jobs:
  flake-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix Flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Allow direnv
        run: nix develop .#default -c direnv allow .

      - name: Export direnv
        run: nix develop .#default -c direnv export gha >> "$GITHUB_ENV"

      - name: Run hadolint
        run: hadolint Dockerfile
